### ISSUE TITLE
Merge changes from Images version of juicy-filedrop.html

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-upload#3]
In this commit https://github.com/StarcounterPrefabs/Images/commit/bdc2dc74304c607f1037320ea5a3bdf0b6ec27da#diff-238cbd0e713c7b9af27a4efdf7aa6c9cR115 some problem with file upload dialog was fixed. 

This fix should also land in https://github.com/Starcounter/starcounter-upload

Please always remember to maintain the original/related file when you fix to a problem.

**Comment by aloscha** [comment]
Here is a pr https://github.com/Starcounter/starcounter-upload/pull/4

**Comment by warpech** [comment]
Thanks!
