### ISSUE TITLE
Typo inside starcounter-upload

### ISSUE THREAD

**Issue by Joltrix** [Starcounter/starcounter-upload#5]
inside starcounter-upload.html there is a function called isSumbitVisible,

I'm guessing that should be isSubmitVisible?

(Not sure if this is "important enough" to qualify as an issue but I just thought I'd at least let you know ~)

cc @warpech

**Comment by warpech** [comment]
Yeah, everything is important, especially such low hanging fruits are nice when you want to have a feel good sensation of fixing something :) Feel free to fix that, but the priority is not big at all

**Comment by miyconst** [comment]
@Joltrix I thought you were talking about the `starcounter-include`, since it is in `starcounter-upload` feel free to fix it and release a new version, then install wherever it is needed 😄.
